### ISSUE TITLE
Crash!!

### ISSUE THREAD

**Issue by Correct-Syntax** [ttddee/Cascade#2]
Hey there,

So I did want to try out your application, but on launch it crashes. :(

Computer specs:
Win 10 
64 bit
AMD gpu
Ryzen 7 cpu

I didn't even get an error message in the CMD when I tried running it from there. The window pops-up for about two seconds but then crashes.

BTW,  the nodes are not really my style(!), but otherwise this looks great. It actually reminds me of an application I had found on the Windows store (yours looks very similar to it).

**Edit:** This is the application I was talking about: [link](https://www.microsoft.com/en-us/p/electric-image-editor/9ng3qp4cxqnd). It looks so similar to yours, so I was curious if it was your inspiration for Cascade?

Thanks.

**Comment by ttddee** [comment]
Hey,

thanks for the feedback! Can you tell me the name of your GPU?

I have only tested on Nvidia GPUs so far, will investigate.

**Comment by Correct-Syntax** [comment]
AMD Radeon RX Vega 10  Graphics -for display (integrated)
AMD Radeon RX 560x series -discrete

**Comment by ttddee** [comment]
The Vega 10 card is not officially supported by Vulkan. Your discrete card is though.

I have added some code to always prefer a discrete GPU over an integrated one. Since I can't test this on my system it might not be stable but if you want to give it a try that would be great.

There now is a log file in the application directory called *cascade.log*, so in case of a crash it is a bit easier to figure out what happened.

The release is [here](https://github.com/ttddee/Cascade/releases/tag/v0.1.2-pre-alpha)

**Comment by Correct-Syntax** [comment]
Again, same thing.
[cascade.log](https://github.com/ttddee/Cascade/files/5461618/cascade.log)

**Comment by ttddee** [comment]
I think/hope this should be fixed now in the new [release](https://github.com/ttddee/Cascade/releases/tag/v0.1.4-pre-alpha).

**Comment by Correct-Syntax** [comment]
Yes, the full Ui shows up now. However, I don't understand how you preview the image node results etc.  It just shows black or white no matter what image I open or node setup there is. The F1, F2, F3 shortcuts don't make any difference (just black or white in the preview). Strange.

**Comment by ttddee** [comment]
If you click on the read node and press F4?

**Comment by Correct-Syntax** [comment]
Yep. Same thing. Not working at all. Just black or white like a toggle when the F4 key is pressed.
