### ISSUE TITLE
About PNGs

### ISSUE THREAD

**Issue by benthillerkus** [ttddee/Cascade#3]
I saw in the release notes that PNGs are supported now. Considering that they are a pretty terrible image format, isn't supporting them for output a bit of an anti-feature?

**Comment by ttddee** [comment]
Uhm I don't know any image processing software that doesn't support them and PNGs run half the internet. 

So, not sure how to reply to this. You don't like them? That's fine! It doesn't cost anything to support them, just an additional flag passed to a function.

**Comment by benthillerkus** [comment]
I guess you're right, my train of thought was that it might be in the users interest to not be able to create PNGs, as it would spare the user from having to deal with PNG related issues like [slow export speed and size](https://blender.stackexchange.com/questions/148231/what-image-format-encodes-the-fastest-or-at-least-faster-png-is-too-slow/148466#148466).

**Comment by ttddee** [comment]
Sure every file format has its use case. I wouldn't recommend PNG for saving your 3D renders and what not. But if you want to throw something onto a website and you want lossless compression, it's good for that.

The link you posted talks about rendering of video sequences. That's a very different beast compared to still images. Because you are dealing with 25+ frames per second encoding speed becomes an issue.
